/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackagesPackageIdRouteImport } from './routes/packages/$packageId'
import { Route as GenerateSoundRouteImport } from './routes/generate/sound'
import { Route as GenerateImageRouteImport } from './routes/generate/image'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesPackageIdRoute = PackagesPackageIdRouteImport.update({
  id: '/packages/$packageId',
  path: '/packages/$packageId',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateSoundRoute = GenerateSoundRouteImport.update({
  id: '/generate/sound',
  path: '/generate/sound',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateImageRoute = GenerateImageRouteImport.update({
  id: '/generate/image',
  path: '/generate/image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/generate/image': typeof GenerateImageRoute
  '/generate/sound': typeof GenerateSoundRoute
  '/packages/$packageId': typeof PackagesPackageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/generate/image': typeof GenerateImageRoute
  '/generate/sound': typeof GenerateSoundRoute
  '/packages/$packageId': typeof PackagesPackageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/generate/image': typeof GenerateImageRoute
  '/generate/sound': typeof GenerateSoundRoute
  '/packages/$packageId': typeof PackagesPackageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/library'
    | '/settings'
    | '/generate/image'
    | '/generate/sound'
    | '/packages/$packageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/library'
    | '/settings'
    | '/generate/image'
    | '/generate/sound'
    | '/packages/$packageId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/library'
    | '/settings'
    | '/generate/image'
    | '/generate/sound'
    | '/packages/$packageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LibraryRoute: typeof LibraryRoute
  SettingsRoute: typeof SettingsRoute
  GenerateImageRoute: typeof GenerateImageRoute
  GenerateSoundRoute: typeof GenerateSoundRoute
  PackagesPackageIdRoute: typeof PackagesPackageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$packageId': {
      id: '/packages/$packageId'
      path: '/packages/$packageId'
      fullPath: '/packages/$packageId'
      preLoaderRoute: typeof PackagesPackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/sound': {
      id: '/generate/sound'
      path: '/generate/sound'
      fullPath: '/generate/sound'
      preLoaderRoute: typeof GenerateSoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/image': {
      id: '/generate/image'
      path: '/generate/image'
      fullPath: '/generate/image'
      preLoaderRoute: typeof GenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LibraryRoute: LibraryRoute,
  SettingsRoute: SettingsRoute,
  GenerateImageRoute: GenerateImageRoute,
  GenerateSoundRoute: GenerateSoundRoute,
  PackagesPackageIdRoute: PackagesPackageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
